### PR TITLE
Generate EarlyBound models

### LINKED ISSUE #18: [Feature Request] Generate Entities compatible with @albanian-xrm/early-bound
I know it is much to ask ;) but:
I would like to add an option to generate the EarlyBound models in a slightly different format which is compatible with the new package that I have created: [@albanian-xrm/early-bound](https://github.com/albanian-xrm/xrm-early-bound)
I will issue a PR myself soon for this.

### PR DESCRIPTION
**Pull request by BetimBeja**
:sparkles: This closes #18 
:recycle: refactored tests for reusability

### CODE REVIEW

**Comment by OliverFlint** [comment]
@BetimBeja Apologies, I hadn't noticed this PR. I'll make sure I look at it this week. Thanks for the contribution!!!

**Comment by OliverFlint** [comment]
@BetimBeja So sorry I haven't looked at this until now. Started to go through it last night. Looking to merge it at some point this week  👍

**Comment by BetimBeja** [comment]
No worries. Ping me if you need to suggest any changes to this 😉

**Comment by BetimBeja** [comment]
I am not sure on how important this comparison is, but using my typings on this simple definition the build is faster 😄 
image
image

**Comment by OliverFlint** [comment]
Interesting, although the sample size is very small and the difference is also so small we shouldn't rule out environmental changes between tests.
However, when I find some time to look at this i'll consider it and do some testing.

**Comment by BetimBeja** [comment]
I need to test with a bigger sample and use tracing instead of just measuring using  `--extendedDiagnostics`
https://github.com/microsoft/TypeScript/wiki/Performance#performance-tracing
Traces can be analyzed using https://ui.perfetto.dev/

**Comment by OliverFlint** [comment]
We also need to consider that lots of people will be using other transpilers like webpack, esbuild, etc.

**Comment by BetimBeja** [comment]
I implemented this feature as op-in so that people can choose, also I don't think that using transpilers would be a problem (other than the fact that my typings have a dependency on typescript >=4.2)

**Pull request merged**
